# Generated by Django 5.2.5 on 2025-08-16 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0012_favorite_recreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('STATIC', 'Statique'), ('DESTINATION', 'Destination'), ('REGION', 'Région'), ('CATEGORY', 'Catégorie')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=170)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('keyword', models.CharField(blank=True, max_length=160)),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Thiès', 'Thiès'), ('Diourbel', 'Diourbel'), ('Kaolack', 'Kaolack'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Louga', 'Louga'), ('Saint-Louis', 'Saint-Louis'), ('Matam', 'Matam'), ('Tambacounda', 'Tambacounda'), ('Kédougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Sédhiou', 'Sédhiou'), ('Ziguinchor', 'Ziguinchor')], help_text='RÉGION uniquement.', max_length=20, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('city', 'Citadine'), ('sedan', 'Berline'), ('suv', 'SUV'), ('4x4', '4x4'), ('pickup', 'Pickup'), ('van', 'Monospace / Van'), ('minibus', 'Minibus'), ('bus', 'Bus'), ('car', 'Car'), ('coupe', 'Coupé'), ('conv', 'Cabriolet'), ('other', 'Autre')], help_text='CATÉGORIE : ex. SUV, berline, utilitaire…', max_length=20, null=True)),
                ('content', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, help_text='DESTINATION uniquement.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.city')),
            ],
            options={
                'ordering': ['position', 'title'],
                'indexes': [models.Index(fields=['is_active', 'kind'], name='pages_landi_is_acti_7d6f37_idx'), models.Index(fields=['position'], name='pages_landi_positio_bd2f41_idx')],
            },
        ),
    ]
