# Generated by Django 5.2.5 on 2025-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('Dakar', 'Dakar'), ('Thiès', 'Thiès'), ('Diourbel', 'Diourbel'), ('Kaolack', 'Kaolack'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Louga', 'Louga'), ('Saint-Louis', 'Saint-Louis'), ('Matam', 'Matam'), ('Tambacounda', 'Tambacounda'), ('Kédougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Sédhiou', 'Sédhiou'), ('Ziguinchor', 'Ziguinchor')], default='Dakar', max_length=20),
        ),
    ]
