# Generated by Django 5.2.5 on 2025-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(choices=[('2', '2 portes'), ('3', '3 portes'), ('4', '4 portes'), ('5', '5 portes'), ('6+', '6 ou plus de portes')], default=5, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(choices=[('2', '2 places'), ('3', '3 places'), ('4', '4 places'), ('5', '5 places'), ('6', '6 places'), ('7', '7 places'), ('8', '8 places'), ('9', '9 places'), ('10+', '10 ou plus de places')], default=5, max_length=100),
        ),
    ]
