# Generated by Django 5.2.5 on 2025-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_doors_alter_car_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('city', 'Citadine'), ('sedan', 'Berline'), ('suv', 'SUV'), ('4x4', '4x4'), ('pickup', 'Pickup'), ('van', 'Monospace / Van'), ('minibus', 'Minibus'), ('bus', 'Bus'), ('car', 'Car'), ('coupe', 'Coupé'), ('conv', 'Cabriolet'), ('other', 'Autre')], default='city', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(choices=[('2', '2 portes'), ('3', '3 portes'), ('4', '4 portes'), ('5', '5 portes')], default='2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(choices=[('2', '2 places'), ('3', '3 places'), ('4', '4 places'), ('5', '5 places'), ('6', '6 places'), ('7', '7 places'), ('8', '8 places'), ('9', '9 places')], default='2'),
        ),
    ]
