# Generated by Django 5.2.5 on 2025-08-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_body_type_alter_car_doors_alter_car_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2 portes'), ('3', '3 portes'), ('4', '4 portes'), ('5', '5 portes')], default='2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.CharField(choices=[('2', '2 places'), ('3', '3 places'), ('4', '4 places'), ('5', '5 places'), ('6', '6 places'), ('7', '7 places'), ('8', '8 places'), ('9', '9 places')], default='2'),
        ),
    ]
