# Generated by Django 5.2.5 on 2025-08-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_models', to='cars.carmodel', verbose_name='Modèle'),
        ),
    ]
