# Generated by Django 4.2.11 on 2025-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_favorite_recreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (9999, 'Autre année')], default=2024),
        ),
    ]
